# IMPORTANT: USER REQUIREMENT - WordPress MUST run on port 9000
# phpMyAdmin MUST run on port 9001
# MailHog MUST run on port 9025
# DO NOT CHANGE THESE PORTS WITHOUT USER APPROVAL

services:
  wordpress:
    image: wordpress:6.4-php8.0-apache
    container_name: gary-ai-wordpress
    restart: unless-stopped
    ports:
      - "9000:80"  # USER REQUIREMENT: WordPress on port 9000
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DEBUG: 1
      CONTEXTUAL_API_KEY: ${CONTEXTUAL_API_KEY}
      AGENT_ID: ${AGENT_ID}
      DATASTORE_ID: ${DATASTORE_ID}
      AGENT_NAME: Gary AI
      WORDPRESS_TABLE_PREFIX: wp_
      WORDPRESS_CONFIG_EXTRA: |
        define('WP_DEBUG', true);
        define('WP_DEBUG_LOG', true);
        define('WP_DEBUG_DISPLAY', true);
        define('SCRIPT_DEBUG', true);
        define('WP_DEBUG_DISPLAY_ERRORS', true);
        
        // Enable error logging
        ini_set('log_errors', 1);
        ini_set('error_log', '/var/www/html/wp-content/debug-logs/debug.log');
        
        // Gary AI Plugin Constants
        define('GARY_AI_API_ENDPOINT', 'https://api.contextual.ai/');
        define('GARY_AI_ENCRYPTION_KEY', 'dev-32-byte-encryption-key-test123');
    volumes:
      - wordpress_data:/var/www/html
      - .:/var/www/html/wp-content/plugins/gary-ai:rw
      - ./logs:/var/www/html/wp-content/debug-logs:rw
      - ./envvars.conf:/etc/apache2/conf-enabled/envvars.conf
    depends_on:
      - db
    networks:
      - gary-ai-network

  cli:
    image: wordpress:cli-php8.0
    container_name: gary-ai-cli
    volumes:
      - wordpress_data:/var/www/html
      - .:/var/www/html/wp-content/plugins/gary-ai:rw
    depends_on:
      - db
      - wordpress
    networks:
      - gary-ai-network
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress

  db:
    image: mysql:8.0
    container_name: gary-ai-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - gary-ai-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: gary-ai-phpmyadmin
    restart: unless-stopped
    ports:
      - "9001:80"  # USER REQUIREMENT: phpMyAdmin on port 9001
    environment:
      PMA_HOST: db
      PMA_USER: wordpress
      PMA_PASSWORD: wordpress
    depends_on:
      - db
    networks:
      - gary-ai-network

  # Node.js development environment for testing
  node-dev:
    build:
      context: .
      dockerfile: Dockerfile.node
    container_name: gary-ai-node-dev
    working_dir: /app
    volumes:
      - ./:/app
      - node_modules:/app/node_modules
    ports:
      - "3000:3000"  # Vite dev server
      - "9323:9323"  # Playwright UI
    environment:
      - NODE_ENV=development
    command: tail -f /dev/null  # Keep container running
    networks:
      - gary-ai-network

  # Composer for PHP dependencies
  composer:
    image: composer:latest
    container_name: gary-ai-composer
    working_dir: /app
    volumes:
      - ./:/app
    command: install --no-dev --optimize-autoloader
    networks:
      - gary-ai-network

  # Testing runner service
  test-runner:
    build:
      context: .
      dockerfile: Dockerfile.node
    container_name: gary-ai-test-runner
    working_dir: /app
    volumes:
      - ./:/app
      - node_modules:/app/node_modules
    environment:
      - NODE_ENV=test
      - CI=true
    profiles:
      - testing
    networks:
      - gary-ai-network

  # MailHog for email testing
  mailhog:
    image: mailhog/mailhog:v1.0.1
    container_name: gary-ai-mailhog
    restart: unless-stopped
    ports:
      - "9025:8025"  # USER REQUIREMENT: MailHog on port 9025
      - "1025:1025"  # SMTP
    networks:
      - gary-ai-network

volumes:
  wordpress_data:
  db_data:
  node_modules:

networks:
  gary-ai-network:
    driver: bridge
