version: '3.8'

services:
  wordpress:
    image: wordpress:6.4-php8.0-apache
    container_name: gary-ai-wordpress
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DEBUG: 1
      WORDPRESS_TABLE_PREFIX: wp_
      WORDPRESS_CONFIG_EXTRA: |
        define('WP_DEBUG', true);
        define('WP_DEBUG_LOG', true);
        define('WP_DEBUG_DISPLAY', true);
        define('SCRIPT_DEBUG', true);
        define('WP_DEBUG_DISPLAY_ERRORS', true);
        
        // Enable error logging
        ini_set('log_errors', 1);
        ini_set('error_log', '/var/www/html/wp-content/debug.log');
        
        // Gary AI Plugin Constants
        define('GARY_AI_API_ENDPOINT', 'https://api.contextual.ai/');
        define('GARY_AI_ENCRYPTION_KEY', 'dev-32-byte-encryption-key-test123');
    volumes:
      - wordpress_data:/var/www/html
      - .:/var/www/html/wp-content/plugins/gary-ai:rw
      - ./logs:/var/www/html/wp-content/debug-logs:rw
    depends_on:
      - db
    networks:
      - gary-ai-network

  db:
    image: mysql:8.0
    container_name: gary-ai-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - gary-ai-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: gary-ai-phpmyadmin
    restart: unless-stopped
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      PMA_USER: wordpress
      PMA_PASSWORD: wordpress
    depends_on:
      - db
    networks:
      - gary-ai-network

  # Node.js development environment for testing
  node-dev:
    build:
      context: .
      dockerfile: Dockerfile.node
    container_name: gary-ai-node-dev
    working_dir: /app
    volumes:
      - ./:/app
      - node_modules:/app/node_modules
    ports:
      - "3000:3000"  # Vite dev server
      - "9323:9323"  # Playwright UI
    environment:
      - NODE_ENV=development
    command: tail -f /dev/null  # Keep container running
    networks:
      - gary-ai-network

  # Composer for PHP dependencies
  composer:
    image: composer:latest
    container_name: gary-ai-composer
    working_dir: /app
    volumes:
      - ./:/app
    command: install --no-dev --optimize-autoloader
    networks:
      - gary-ai-network

  # Testing runner service
  test-runner:
    build:
      context: .
      dockerfile: Dockerfile.node
    container_name: gary-ai-test-runner
    working_dir: /app
    volumes:
      - ./:/app
      - node_modules:/app/node_modules
    environment:
      - NODE_ENV=test
      - CI=true
    profiles:
      - testing
    networks:
      - gary-ai-network

volumes:
  wordpress_data:
  db_data:
  node_modules:

networks:
  gary-ai-network:
    driver: bridge
